repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.2.0
    hooks:
    -   id: check-yaml # checks yaml files for parseable syntax
    -   id: check-toml # checks toml files for parseable syntax
    -   id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
    -   id: trailing-whitespace # trims trailing whitespace
    -   id: detect-private-key # detects the presence of private keys
  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
    -   id: black
  - repo: 'https://github.com/akaihola/darker'
    rev: 1.5.0
    hooks:
      - id: darker
        args: [--isort, flake8]
        additional_dependencies:
          - isort
          - flake8
